channels:
- conda-forge
dependencies:
- python=3.13.7
- pip<=25.2
- pip:
  - mlflow==3.3.2
  - cloudpickle==3.1.1
  - matplotlib==3.10.6
  - numpy==2.3.2
  - scikit-learn==1.7.2
  - typing==3.10.0.0
name: mlflow-env
